config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats
  resources :requests

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
require 'action_view'
require 'action_view/helpers'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  validates :birth_date, :color, :sex, :name, :description, presence: true
  #validates :color, inclusion: ["red"]
  validates :color, inclusion: { in: ["red", "orange", "blue", "brown", "black", "white", "yellow", "green"] }
  validates :sex, inclusion: { in: ["M", "F"]}
  def age 
    distance_of_time_in_words(self.birth_date, Date.today)
  end

  def possible_colors
    Cat.validators_on(:color)[1].options[:in]
  end


  has_many :rentals,
    foreign_key: :cat_id,
    class_name: :Catrentalrequest,
    dependent: :destroy
end

app/models/catrentalrequest.rb
class Catrentalrequest < ApplicationRecord

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: {in: ['PENDING', 'APPROVED', 'DENIED']}
  #validate :start_must_come_before_end
  validate :does_not_overlap_approved_request

  belongs_to( :cat,
    foreign_key: :cat_id,
    class_name: :Cat)
    
  def overlapping_requests()
    requests = Catrentalrequest.where(cat_id: self.cat_id)
    requests.where.not(id: self.id)
      .where.not('start_date > :end_date OR end_date < :start_date',
      start_date: start_date, end_date: end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.any?
      errors[:base] << ("Existing approved request")
    end
  end
  #   requests.select {|request| (new_request.start_date < request.end_date) || (new_request.end_date < request.start_date)}
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  def index
    @cats = Cat.all 
    render :index
  end

  def show
    @cat = Cat.find(params[:id])

    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
   new_cat = Cat.new(params.require(:cat).permit(:name, :description, :sex, :color, :birth_date))

    if new_cat.save
      redirect_to cat_url(new_cat)
    else
      render json: new_cat.save.errors.full_messages, status: 422
    end
  end

  def update
    @cat = Cat.new(params.require(:cat).permit(:name, :description, :sex, :color, :birth_date))
    if @cat.persisted?
      @cat = Cat.find(params[:id])
      @cat.update(params.require(:cat).permit(:name, :description, :sex, :color, :birth_date))
      redirect_to cat_url(@cat)
    
    else
      render json: "Something went wrong... :("
      # redirect_to cats_url
    end
  end


  def edit
    @cat = Cat.find(params[:id])
    if @cat
      render :edit
    else
      render json: "Cat does not exist"
    end
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

    def index
        @requests = Catrentalrequest.all.order(:start_date)
        render :index
    end

    def new
        @cats = Cat.all
        render :new
    end

    def create 
        new_request = Catrentalrequest.new(params.require(:request).permit(:cat_id,:start_date, :end_date))
        if new_request.save
            redirect_to requests_url
        else
            render json: new_request.errors.full_messages, status: 422
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/cats/_form.html.erb
<% if type == :new %>
  <%action_choice = cats_url%>
<%else%>
  <%action_choice = cat_url(cat)%>
<%end%>

<form action="<%=action_choice%>" method= "post">
  <% if type == :edit%>
    <input type="hidden" name="_method" value="patch">
  <%end%>

<label for = "name"> Name: 
  <input type= "text" id="name" name="cat[name]" value ="<%= cat.name%>" >
</label>

<label for = "birth_date"> Birthdate: 
  <input type= "date" id="birth_date" name="cat[birth_date]" value ="<%= cat.birth_date%>" >
</label>
<br>
<label for = "gender"> Gender: 
<br>
<%if cat.sex == "M"%>
  <input type= "radio" id="gender" name="cat[sex]" value ="M" checked> Male <br>
  <input type= "radio" id="gender" name="cat[sex]" value ="F"> Female <br>
<%else%>
  <input type= "radio" id="gender" name="cat[sex]" value ="M" > Male <br>
  <input type= "radio" id="gender" name="cat[sex]" value ="F" checked> Female <br>
<%end%>
</label>

<label for = "color"> Color: 
<select id="color" name="cat[color]">
<%cat.possible_colors.each do |color|%>
  <%if color == cat.color%>
  <option value ="<%=color%>" selected="selected"> <%=color%> </option>
  <%else%>
  <option value ="<%=color%>"> <%=color%></option>
  <%end%>
<%end%>
</select>
</label>

<label for = "description"> Description: 
  <textarea type="text" id="description" name="cat[description]" value ="<%= cat.description%>" ><%=cat.description%>
  </textarea>
</label>

<input type="submit" value = "submit">
</form>

app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, type: :edit %>

app/views/cats/index.html.erb
<ul>
  <%@cats.each do |cat|%>
 <li>
  <ul>
    <li><%=cat.name%></li>
    <li><%=cat.age%></li>
    <li><%=cat.sex%></li>
    <li><%=cat.color%></li>
    <li><%=cat.description%></li>
    <li><a href="<%=cat_url(cat)%>">Cat's Page </a></li>
  </ul>
  <br>

  </li>
  <%end%>
</ul>

<a href="<%=new_cat_url%>">New Cat </a>

app/views/cats/new.html.erb
<%= render 'form', cat: @cat, type: :new %>

app/views/cats/show.html.erb
<style>
table,
td {
    border: 1px solid #333;
}

thead,
tfoot {
    background-color: #333;
    color: #fff;
}
</style>


<table>
    <thead>
        <tr>
            <th colspan="2"><%=@cat.name%></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>color</td>
            <td><%=@cat.color%></td>
        </tr>
        <tr>
            <td>Age</td>
            <td><%=@cat.age%></td>
        </tr>
        <tr>
            <td>Gender</td>
            <td><%=@cat.sex%></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%=@cat.description%></td>
        </tr>
    </tbody>
</table>
<br>

<a href="<%=edit_cat_url(@cat)%>">Edit </a>
<br>


<a href="<%=cats_url%>">Home </a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/requests/index.html.erb
<table>
    <tr>
        <th> Start Date</th>
        <th> End Date</th>
    </tr>
<% @requests.each do |r| %>
    <tr>
        <th> <%= r.start_date %> </th>
        <th> <%= r.end_date %> </th>
    </tr>
    
<% end %>

</table>

app/views/requests/new.html.erb
<form action="<%=requests_url%>" method="post">
    <label for = "catname"> Cat Name:
        <select id = "catname" name="request[cat_id]">
        <% @cats.each do |cat| %>
            <option value="<%= cat.id %>" > <%= cat.name %></option>
        <% end %>
        </select>
    </label>
    <label for = "start_date"> Start_date: 
        <input type= "date" id="start_date" name="request[start_date]">
    </label>
    <br>
    <label for = "end_date"> End_date: 
        <input type= "date" id="end_date" name="request[end_date]">
    </label>
    <br>
    <input type="submit" value = "submit">
</form>